export const KIDS_AVATARS = [
  '🦁', '🐘', '🦒', '🦓', '🦘', '🐨', '🐼', '🦊', '🐰', '🐸'
];

export const COLORS = {
  primary: '#FF6B6B',
  secondary: '#4ECDC4',
  accent: '#FFE66D',
  background: '#F7FFF7',
  text: '#2F3061',
};

export const ACTIVITIES = [
  {
    id: 'tracing',
    title: 'Letter Safari',
    description: 'Trace letters to find animals!',
    icon: '✍️',
    minAge: 4,
    color: 'bg-pink-400',
  },
  {
    id: 'spelling',
    title: 'Word Bubbles',
    description: 'Pop bubbles to spell words!',
    icon: '🫧',
    minAge: 6,
    color: 'bg-blue-400',
  },
  {
    id: 'story',
    title: 'AI Story Buddy',
    description: 'Create your own magic story!',
    icon: '🪄',
    minAge: 4,
    color: 'bg-purple-400',
  },
  {
    id: 'maze',
    title: 'Maze Runner',
    description: 'Help the animal find its home!',
    icon: '🌀',
    minAge: 4,
    color: 'bg-orange-400',
  },
  {
    id: 'hidden',
    title: 'Spy Glass',
    description: 'Find the hidden treasures!',
    icon: '🔍',
    minAge: 4,
    color: 'bg-green-400',
  },
  {
    id: 'sky',
    title: 'Sky Rescue',
    description: 'Save the plane from obstacles!',
    icon: '🛩️',
    minAge: 4,
    color: 'bg-blue-400',
  },
  {
    id: 'bubble',
    title: 'Bubble Catch',
    description: 'Catch the right letter bubbles!',
    icon: '🫧',
    minAge: 4,
    color: 'bg-cyan-400',
  },
  {
    id: 'math',
    title: 'Math Magic',
    description: 'Count, add, and subtract with fun visual puzzles!',
    icon: '🪄',
    color: 'bg-cyan-500',
    minAge: 4, // You can adjust this based on the difficulty!
    isNew: true
  },
  {
    id: 'mole',
    title: 'Whack-a-Mole',
    description: 'Tap the moles as they pop up!',
    icon: '🐹',
    minAge: 4,
    color: 'bg-amber-600',
  },
  {
    id: 'phonics',
    title: 'Phonics Sing-Along',
    description: 'Tap letters to hear their sounds!',
    icon: '🎵',
    minAge: 4,
    color: 'bg-purple-500',
    isNew: true,
  },
  {
    id: 'rhyme',
    title: 'Rhyme Time',
    description: 'Find the picture that rhymes!',
    icon: '🐱',
    minAge: 4,
    color: 'bg-green-500',
    isNew: true,
  },
  {
    id: 'bounce',
    title: 'First Letter Bounce',
    description: 'Tap the starting letter fast!',
    icon: '🏀',
    minAge: 4,
    color: 'bg-orange-500',
    isNew: true,
  },
  {
    id: 'match',
    title: 'Letter Match Pairs',
    description: 'Match big A with little a!',
    icon: '🃏',
    minAge: 4,
    color: 'bg-indigo-500',
    isNew: true,
  },
  {
    id: 'sentence',
    title: 'Sentence Builder',
    description: 'Drag words to build sentences!',
    icon: '🏗️',
    minAge: 5,
    color: 'bg-teal-500',
    isNew: true,
  },
  {
    id: 'sequence',
    title: 'Story Sequencing',
    description: 'Put the story in the right order!',
    icon: '📖',
    minAge: 5,
    color: 'bg-pink-500',
    isNew: true,
  },
  {
    id: 'wordfamily',
    title: 'Word Family House',
    description: 'Build word families like CAT, BAT, HAT!',
    icon: '🏠',
    minAge: 5,
    color: 'bg-amber-500',
    isNew: true,
  },
];
